---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts.fullname" . }}-frontend
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
data:
  {{- with .Values.frontend.config }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts.fullname" . }}-backend
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
data:
  {{- with .Values.backend.config }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
