{{- if .Values.ingress.enabled -}}
{{- $fullName := include "accounts.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | squote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- $svc := .Values.service }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . | squote }}
      http:
        paths:
          - path: /api
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svc.backendPort }}
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svc.frontendPort }}
    {{- end }}
  {{- end }}
