apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts.fullname" . }}
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
data:
{{- with .Values.backend.secrets }}
  STRIPE_PRIVATE_KEY: {{ required "Stripe private key is required" .stripePrivateKey | b64enc }}
  STRIPE_ENDPOINT_SECRET: {{ required "Stripe endpoint secret is required" .stripeEndpointSecret | b64enc }}
  IAM_JWT: {{ required "IAM JWT is required" .iamJWT | b64enc }}
{{- end }}
