apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ma1sd.fullname" . }}
  labels:
    {{- include "ma1sd.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  ma1sd.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
