apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webspaced.fullname" . }}
  labels:
    {{- include "webspaced.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  webspaced.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
