apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webspaced.fullname" . }}
  labels:
    {{- include "webspaced.labels" . | nindent 4 }}
data:
  iam_token.txt: {{ .Values.secrets.iamToken | b64enc }}
  lxd_client.key: {{ .Values.secrets.lxdKey | b64enc }}
  lxd_trust.txt: {{ .Values.secrets.lxdTrust | b64enc | squote }}
  traefik_iam_token.txt: {{ .Values.secrets.traefikIAMToken | b64enc }}
